sudo: false

language: php

php:
    - 7.0
    - 7.1

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > ~/.composer/auth.json
    - composer install --prefer-dist
    - composer create-project --repository=https://repo.magento.com magento/marketplace-eqp marketplace-eqp

script:
    - php marketplace-eqp/vendor/bin/phpcs Model/ Observer/ Plugin/ Setup/ Test/ view/  --standard=MEQP2 --severity=10
    - php vendor/bin/phpmd Model/,Observer/,Plugin/,Test/,view/ text cleancode,codesize,controversial,design,naming,unusedcode --ignore-violations-on-exit
    - php vendor/phpunit/phpunit/phpunit --coverage-clover Test/Unit/logs/clover.xml Test

after_script:
    - php vendor/bin/php-coveralls -v

env:
    global:
        - secure: "QczP3j78fN0ALVwWT3QX/nAzg7v1whD9I4t2Jd2UK9zNdEG649L1QVfmYnwZONbxlSFLkRirQAshBSpal6thDbkU8B/qbgSAvzLMl+hVdLKwSMVH7hgD/C+HXVuGczVEktpOgmMDPTUdaq5+381mSjIx0I1HMeWMPHOWlrfNL7vOsM90NgH5zeeEWTfURB54BKYbnNo4TTKdg0DMUwMTyz2/RqX4doILwHPwF02ekmV9ld90pupLXfhdE5+JVdBP69veqcIMrmjt4dl5ZoDoKCLvDwz/LbG7J3wvFH3TrDbRJCA5KPoOYqxlkYgF1xxkE0ykZWch2rpBl+LbQYQb0uU4G8V4wWigfEDlW2IbVvwh8XNAmykuEdtcltVqdwiW7xBoH5Xr0PiMU9pBqJ+beGYATIMCtgfO7Hurjf+/vxtYw4fHn/b5FPdRM8KMofEGPiqrIIw+GZwNHtL/wWxlOv0yb+45J2vdpC40daghUjsRDWr9TRrXzGTbETwTWL5Bnwrpo80BiTuBpMSDlwuPz07CL7jJC2U/Wrkzh0xMK0stCTLo0iSwDk77h75j0713vtxLCBEXzLYeHwqb9Ppg3hcGlxAjk0+l1anEXLcKWgNLJNYM9UzToj8+EbdwCTnVIzEalp3xT2GDgdGOE+ET5h3ixKNf2+S7TXvUuZVlJJo="
        - secure: "Fk56VesPIBjY+UwH68zqquhcr8iTXbvkdbC/I5h/9z2aTBTfC4FAZcDtsfx5/C1fKf4mtScAfs7gSQUjCk/OATxv4DqugJhwZTZu6hr0PJHimvnIqcwyV7Zk5fClcTU6ESYuK1hAbkEQA7pO394R3Gg1JBp50DSUgZM1qdGLDl7xWpSMzBzb2OMfACwo115Ao8+Evy1OgS4fshW4aP1bFH2/AAH3Mr1WYa1oXoDSJbpqSMsys80LpZXXe55VuD9l6ZquhZrvrAL4om2GhqqkDp6pBxmjMDVy0xy8Kajbvbba1jGgZi8YVIkWnJaRECU9gRVSa2ZXkRK1f8jLoo2e7+E5ri+/fIs3vrV8iqGFHQjI/7wCYnZqthm056mAkverVL2fJw8PNs7vw/k3Ph8a9WqT2ozb13lmre1VIEerFA/c2O5WWpZJfSRpBOVtxadmPKsnUTytusuWPtGbPs4E4dgHnX8BAGGE4YgZokEuYJHXaZYaE8IUXBKlv8MTrjspYtnzwLvC9yD2Cjl7ocALLVsDL+4htwjEet1jAGypBz5VjDeBsRwh3b1CcUWpj1sbyaotIiS9Uu2zmHotzE714HGJXmGr/jg1E/Mvbz9y/Izly97iZRblqRw2Xvchs2g1LrWnIkxWgQZl7+zGVEfu8OhUuuB0NwAH44eSGsH3Aao="
